[devshell]
name = "wrds-tools"

[[commands]]
package = "tabiew"
name = "tw"
help = "View and query CSV/TSV files"
category = "data"

[[commands]]
package = "bat"
help = "Cat with syntax highlighting"
category = "file"

[[commands]]
package = "ripgrep"
name = "rg"
help = "Fast recursive grep"
category = "search"

[[commands]]
package = "fd"
help = "Fast file finder"
category = "search"

[[commands]]
package = "fzf"
help = "Fuzzy finder"
category = "search"

[[commands]]
package = "xan"
help = "CSV processing tool"
category = "data"

[[commands]]
package = "eza"
help = "Modern ls replacement"
category = "file"

[[commands]]
package = "zoxide"
help = "Smarter cd"
category = "navigation"

[[commands]]
package = "jq"
help = "JSON processor"
category = "data"

[[commands]]
package = "dust"
help = "Disk usage analyzer"
category = "file"

[[commands]]
package = "btop"
help = "System monitor"
category = "system"

[[commands]]
package = "yazi"
help = "Terminal file manager"
category = "file"

[[commands]]
package = "direnv"
help = "Environment variable management"
category = "env"

[[commands]]
package = "starship"
help = "Cross-shell prompt"
category = "shell"

[[commands]]
package = "stow"
help = "Symlink manager"
category = "file"

[[commands]]
package = "zsh"
help = "Z shell"
category = "shell"

[[commands]]
package = "gh"
help = "GitHub CLI"
category = "dev"

[[commands]]
package = "tldr"
help = "Simplified man pages"
category = "help"

[[commands]]
package = "p7zip"
help = "Archive utility"
category = "file"

[[commands]]
package = "parallel"
help = "Run commands in parallel"
category = "system"

[[commands]]
package = "poppler"
help = "PDF utilities"
category = "doc"

[[commands]]
package = "resvg"
help = "SVG renderer"
category = "graphics"

[[commands]]
package = "tectonic"
help = "LaTeX engine"
category = "doc"

[[commands]]
package = "rclone"
help = "Cloud storage sync"
category = "sync"

[devshell.startup.wrds-motd]
text = '''
echo "🚀 WRDS DevShell loaded with portable tools"
echo "Run 'menu' to see available commands"
'''