name: Build WRDS DevShell Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build portable bundle
      timeout-minutes: 30
      run: |
        ./build.sh

    - name: Upload bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: wrds-devshell-bundle
        path: wrds-devshell.portable
        retention-days: 30

    - name: Display bundle info
      run: |
        echo "Bundle size: $(du -sh wrds-devshell.portable | cut -f1)"
        echo "Bundle created successfully!"